package orm.models;

import org.jooq.DSLContext;
import org.jooq.UpdatableRecord;
import orm.Model;

/**
 * The {@code PersistableModel3} should be used for models that needs three {@link UpdatableRecord} to be persisted into
 * the database. Each time a {@link UpdatableRecord} has been persisted, as it has been refreshed with the autogenerated
 * * fields, it is provided back to the model to refresh those particular fields.
 *
 * @param <M> the specific {@link Model}.
 * @param <R1> the first precise subtype of {@link UpdatableRecord}.
 * @param <R2> the second precise subtype of {@link UpdatableRecord}.
 * @param <R3> the third precise subtype of {@link UpdatableRecord}.
 */
public interface PersistableModel3<M extends Model,
    R1 extends UpdatableRecord<R1>,
    R2 extends UpdatableRecord<R2>,
    R3 extends UpdatableRecord<R3>> extends PersistableModel2<M, R1, R2> {

  /**
   * Creates the instance of {@link R2}, matching this model.
   *
   * @param dslContext the {@link DSLContext}.
   *
   * @return the {@link R3}.
   */
  R3 createRecord3(DSLContext dslContext);

  /**
   * Refreshes the model with the updated {@link R3}.
   *
   * @param r3 the {@link R3}, that has been refreshed from the database with autogenerated fields.
   */
  void refresh3(R3 r3);

}
