package orm.models;

import org.jooq.DSLContext;
import org.jooq.UpdatableRecord;
import orm.Model;

/**
 * The {@code PersistableModel2} should be used for models that needs two {@link UpdatableRecord} to be persisted into
 * the database. Each time a {@link UpdatableRecord} has been persisted, as it has been refreshed with the autogenerated
 * fields, it is provided back to the model to refresh those particular fields.
 *
 * @param <M> the specific {@link Model}.
 * @param <R1> the first precise subtype of {@link UpdatableRecord}.
 * @param <R2> the second precise subtype of {@link UpdatableRecord}.
 */
public interface PersistableModel2<M extends Model,
    R1 extends UpdatableRecord<R1>,
    R2 extends UpdatableRecord<R2>> extends PersistableModel1<M, R1> {

  /**
   * Creates the instance of {@link R2}, matching this model.
   *
   * @param dslContext the {@link DSLContext}.
   *
   * @return the {@link R2}.
   */
  R2 createRecord2(DSLContext dslContext);

  /**
   * Refresh the model with the updated {@link R2}.
   *
   * @param r2 the {@link R2}, that has been refreshed from the database with autogenerated fields.
   */
  void refresh2(R2 r2);

}
