package orm.models;

import org.jooq.DSLContext;
import org.jooq.UpdatableRecord;

/**
 * The {@code PersistableModel1} should be used for models that only needs one {@link UpdatableRecord} to be persisted
 * into the database.
 *
 * @param <R> the precise subtype of {@link UpdatableRecord}.
 */
public interface PersistableModel1<R extends UpdatableRecord<R>> extends PersistableModel {

  /**
   * Creates the instance of {@link R}, matching this model.
   *
   * @param dslContext the {@link DSLContext}.
   *
   * @return the {@link R}.
   */
  R createRecord1(DSLContext dslContext);

  /**
   * Refresh the model with the updated {@link R}.
   *
   * @param r the {@link R}, that has been refreshed from the database with autogenerated fields.
   */
  void refresh1(R r);

}
