package orm.models;

import org.jooq.DSLContext;
import org.jooq.UpdatableRecord;

/**
 * The {@code PersistableModel1} should be used for models that only needs one {@link org.jooq.Record} to be persisted
 * into the database.
 *
 * @param <R> the precise subtype of {@link UpdatableRecord}.
 */
public interface PersistableModel1<R extends UpdatableRecord<R>> extends PersistableModel {

  /**
   * Returns the {@link org.jooq.Record}.
   *
   * @param dslContext the {@link DSLContext}.
   *
   * @return the {@link org.jooq.Record}.
   */
  R getUpdatableRecord(DSLContext dslContext);

  /**
   * Refresh the model with the {@link org.jooq.Record}.
   *
   * @param r the {@link org.jooq.Record}, that has been refreshed from the database with autogenerated fields.
   */
  void lastRefresh(R r);

}
