cache:
  paths:
    - .m2/repository

stages:
  - dependencies
  - style
  - build
  - test

dependencies:
  stage: dependencies
  tags:
    - sbt-java17
  script:
    - sbt dependencyUpdates

checkstyle_check:
  stage: style
  tags:
    - sbt-java17
  script:
    - sbt checkstyle

build:
  stage: build
  tags:
    - sbt-java17
  script:
    - sbt clean compile

test:
  stage: test
  tags:
    - sbt-java17
  script:
    - sbt jacoco
