/*
 * This file is generated by jOOQ.
 */
package jooq;


import javax.annotation.processing.Generated;

import jooq.tables.Account;
import jooq.tables.Administrator;
import jooq.tables.AllowedItemTypes;
import jooq.tables.BricklinkTokens;
import jooq.tables.BricksetTokens;
import jooq.tables.Color;
import jooq.tables.ColorInfo;
import jooq.tables.ColorSource;
import jooq.tables.Configuration;
import jooq.tables.Constants;
import jooq.tables.Container;
import jooq.tables.ContainerComposition;
import jooq.tables.ContainerType;
import jooq.tables.ItemSubType;
import jooq.tables.ItemType;
import jooq.tables.LockedAccount;
import jooq.tables.Locker;
import jooq.tables.LockerSize;
import jooq.tables.PrivateContainer;
import jooq.tables.RebrickableTokens;
import jooq.tables.Rgba;
import jooq.tables.SharedContainer;


/**
 * Convenience access to all tables in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.account</code>.
     */
    public static final Account ACCOUNT = Account.ACCOUNT;

    /**
     * The table <code>public.administrator</code>.
     */
    public static final Administrator ADMINISTRATOR = Administrator.ADMINISTRATOR;

    /**
     * The table <code>public.allowed_item_types</code>.
     */
    public static final AllowedItemTypes ALLOWED_ITEM_TYPES = AllowedItemTypes.ALLOWED_ITEM_TYPES;

    /**
     * The table <code>public.bricklink_tokens</code>.
     */
    public static final BricklinkTokens BRICKLINK_TOKENS = BricklinkTokens.BRICKLINK_TOKENS;

    /**
     * The table <code>public.brickset_tokens</code>.
     */
    public static final BricksetTokens BRICKSET_TOKENS = BricksetTokens.BRICKSET_TOKENS;

    /**
     * The table <code>public.color</code>.
     */
    public static final Color COLOR = Color.COLOR;

    /**
     * The table <code>public.color_info</code>.
     */
    public static final ColorInfo COLOR_INFO = ColorInfo.COLOR_INFO;

    /**
     * The table <code>public.color_source</code>.
     */
    public static final ColorSource COLOR_SOURCE = ColorSource.COLOR_SOURCE;

    /**
     * The table <code>public.configuration</code>.
     */
    public static final Configuration CONFIGURATION = Configuration.CONFIGURATION;

    /**
     * The table <code>public.constants</code>.
     */
    public static final Constants CONSTANTS = Constants.CONSTANTS;

    /**
     * The table <code>public.container</code>.
     */
    public static final Container CONTAINER = Container.CONTAINER;

    /**
     * The table <code>public.container_composition</code>.
     */
    public static final ContainerComposition CONTAINER_COMPOSITION = ContainerComposition.CONTAINER_COMPOSITION;

    /**
     * The table <code>public.container_type</code>.
     */
    public static final ContainerType CONTAINER_TYPE = ContainerType.CONTAINER_TYPE;

    /**
     * The table <code>public.item_sub_type</code>.
     */
    public static final ItemSubType ITEM_SUB_TYPE = ItemSubType.ITEM_SUB_TYPE;

    /**
     * item_type is considered as a table of constants, there is not sequence.
     */
    public static final ItemType ITEM_TYPE = ItemType.ITEM_TYPE;

    /**
     * The table <code>public.locked_account</code>.
     */
    public static final LockedAccount LOCKED_ACCOUNT = LockedAccount.LOCKED_ACCOUNT;

    /**
     * The table <code>public.locker</code>.
     */
    public static final Locker LOCKER = Locker.LOCKER;

    /**
     * The table <code>public.locker_size</code>.
     */
    public static final LockerSize LOCKER_SIZE = LockerSize.LOCKER_SIZE;

    /**
     * The table <code>public.private_container</code>.
     */
    public static final PrivateContainer PRIVATE_CONTAINER = PrivateContainer.PRIVATE_CONTAINER;

    /**
     * The table <code>public.rebrickable_tokens</code>.
     */
    public static final RebrickableTokens REBRICKABLE_TOKENS = RebrickableTokens.REBRICKABLE_TOKENS;

    /**
     * The table <code>public.rgba</code>.
     */
    public static final Rgba RGBA = Rgba.RGBA;

    /**
     * The table <code>public.shared_container</code>.
     */
    public static final SharedContainer SHARED_CONTAINER = SharedContainer.SHARED_CONTAINER;
}
