/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jooq.tables.Administrator;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "administrator",
    schema = "public"
)
public class AdministratorRecord extends UpdatableRecordImpl<AdministratorRecord> {

    private static final long serialVersionUID = 1565717579;

    /**
     * Setter for <code>public.administrator.id_account</code>.
     */
    public AdministratorRecord setIdAccount(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.administrator.id_account</code>.
     */
    @Id
    @Column(name = "id_account", nullable = false)
    @NotNull
    @Nonnull
    public Long getIdAccount() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdministratorRecord
     */
    public AdministratorRecord() {
        super(Administrator.ADMINISTRATOR);
    }

    /**
     * Create a detached, initialised AdministratorRecord
     */
    @ConstructorProperties({ "idAccount" })
    public AdministratorRecord(@Nonnull Long idAccount) {
        super(Administrator.ADMINISTRATOR);

        setIdAccount(idAccount);
        resetChangedOnNotNull();
    }
}
