/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jooq.tables.AllowedItemTypes;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "allowed_item_types",
    schema = "public"
)
public class AllowedItemTypesRecord extends UpdatableRecordImpl<AllowedItemTypesRecord> {

    private static final long serialVersionUID = 1890713328;

    /**
     * Setter for <code>public.allowed_item_types.id_container_type</code>.
     */
    public AllowedItemTypesRecord setIdContainerType(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.allowed_item_types.id_container_type</code>.
     */
    @Column(name = "id_container_type", nullable = false)
    @NotNull
    @Nonnull
    public Long getIdContainerType() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.allowed_item_types.id_item_type</code>.
     */
    public AllowedItemTypesRecord setIdItemType(@Nonnull Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.allowed_item_types.id_item_type</code>.
     */
    @Column(name = "id_item_type", nullable = false)
    @NotNull
    @Nonnull
    public Long getIdItemType() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllowedItemTypesRecord
     */
    public AllowedItemTypesRecord() {
        super(AllowedItemTypes.ALLOWED_ITEM_TYPES);
    }

    /**
     * Create a detached, initialised AllowedItemTypesRecord
     */
    @ConstructorProperties({ "idContainerType", "idItemType" })
    public AllowedItemTypesRecord(@Nonnull Long idContainerType, @Nonnull Long idItemType) {
        super(AllowedItemTypes.ALLOWED_ITEM_TYPES);

        setIdContainerType(idContainerType);
        setIdItemType(idItemType);
        resetChangedOnNotNull();
    }
}
