/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jooq.tables.AllowedItemTypes;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "allowed_item_types",
    schema = "public"
)
public class AllowedItemTypesRecord extends UpdatableRecordImpl<AllowedItemTypesRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -950997893;

    /**
     * Setter for <code>public.allowed_item_types.id_container_type</code>.
     */
    public AllowedItemTypesRecord setIdContainerType(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.allowed_item_types.id_container_type</code>.
     */
    @Column(name = "id_container_type", nullable = false, precision = 64)
    @NotNull
    @Nonnull
    public Long getIdContainerType() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.allowed_item_types.id_item_type</code>.
     */
    public AllowedItemTypesRecord setIdItemType(@Nonnull Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.allowed_item_types.id_item_type</code>.
     */
    @Column(name = "id_item_type", nullable = false, precision = 64)
    @NotNull
    @Nonnull
    public Long getIdItemType() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Long> field1() {
        return AllowedItemTypes.ALLOWED_ITEM_TYPES.ID_CONTAINER_TYPE;
    }

    @Override
    @Nonnull
    public Field<Long> field2() {
        return AllowedItemTypes.ALLOWED_ITEM_TYPES.ID_ITEM_TYPE;
    }

    @Override
    @Nonnull
    public Long component1() {
        return getIdContainerType();
    }

    @Override
    @Nonnull
    public Long component2() {
        return getIdItemType();
    }

    @Override
    @Nonnull
    public Long value1() {
        return getIdContainerType();
    }

    @Override
    @Nonnull
    public Long value2() {
        return getIdItemType();
    }

    @Override
    @Nonnull
    public AllowedItemTypesRecord value1(@Nonnull Long value) {
        setIdContainerType(value);
        return this;
    }

    @Override
    @Nonnull
    public AllowedItemTypesRecord value2(@Nonnull Long value) {
        setIdItemType(value);
        return this;
    }

    @Override
    @Nonnull
    public AllowedItemTypesRecord values(@Nonnull Long value1, @Nonnull Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllowedItemTypesRecord
     */
    public AllowedItemTypesRecord() {
        super(AllowedItemTypes.ALLOWED_ITEM_TYPES);
    }

    /**
     * Create a detached, initialised AllowedItemTypesRecord
     */
    @ConstructorProperties({ "idContainerType", "idItemType" })
    public AllowedItemTypesRecord(@Nonnull Long idContainerType, @Nonnull Long idItemType) {
        super(AllowedItemTypes.ALLOWED_ITEM_TYPES);

        setIdContainerType(idContainerType);
        setIdItemType(idItemType);
    }
}
