/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import java.beans.ConstructorProperties;
import java.time.LocalDate;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;

import jooq.tables.BricklinkTokens;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "bricklink_tokens",
    schema = "public"
)
public class BricklinkTokensRecord extends UpdatableRecordImpl<BricklinkTokensRecord> implements Record6<Long, String, String, String, String, LocalDate> {

    private static final long serialVersionUID = 1291915686;

    /**
     * Setter for <code>public.bricklink_tokens.id_account</code>.
     */
    public BricklinkTokensRecord setIdAccount(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.bricklink_tokens.id_account</code>.
     */
    @Id
    @Column(name = "id_account", nullable = false, precision = 64)
    @NotNull
    @Nonnull
    public Long getIdAccount() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.bricklink_tokens.consumer_key</code>.
     */
    public BricklinkTokensRecord setConsumerKey(@Nonnull String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.bricklink_tokens.consumer_key</code>.
     */
    @Column(name = "consumer_key", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    public String getConsumerKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.bricklink_tokens.consumer_secret</code>.
     */
    public BricklinkTokensRecord setConsumerSecret(@Nonnull String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.bricklink_tokens.consumer_secret</code>.
     */
    @Column(name = "consumer_secret", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    public String getConsumerSecret() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.bricklink_tokens.token_value</code>.
     */
    public BricklinkTokensRecord setTokenValue(@Nonnull String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.bricklink_tokens.token_value</code>.
     */
    @Column(name = "token_value", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    public String getTokenValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.bricklink_tokens.token_secret</code>.
     */
    public BricklinkTokensRecord setTokenSecret(@Nonnull String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.bricklink_tokens.token_secret</code>.
     */
    @Column(name = "token_secret", nullable = false, length = 64)
    @NotNull
    @Size(max = 64)
    @Nonnull
    public String getTokenSecret() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.bricklink_tokens.valid_until</code>.
     */
    public BricklinkTokensRecord setValidUntil(@Nonnull LocalDate value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.bricklink_tokens.valid_until</code>.
     */
    @Column(name = "valid_until", nullable = false)
    @Nonnull
    public LocalDate getValidUntil() {
        return (LocalDate) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row6<Long, String, String, String, String, LocalDate> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row6<Long, String, String, String, String, LocalDate> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Long> field1() {
        return BricklinkTokens.BRICKLINK_TOKENS.ID_ACCOUNT;
    }

    @Override
    @Nonnull
    public Field<String> field2() {
        return BricklinkTokens.BRICKLINK_TOKENS.CONSUMER_KEY;
    }

    @Override
    @Nonnull
    public Field<String> field3() {
        return BricklinkTokens.BRICKLINK_TOKENS.CONSUMER_SECRET;
    }

    @Override
    @Nonnull
    public Field<String> field4() {
        return BricklinkTokens.BRICKLINK_TOKENS.TOKEN_VALUE;
    }

    @Override
    @Nonnull
    public Field<String> field5() {
        return BricklinkTokens.BRICKLINK_TOKENS.TOKEN_SECRET;
    }

    @Override
    @Nonnull
    public Field<LocalDate> field6() {
        return BricklinkTokens.BRICKLINK_TOKENS.VALID_UNTIL;
    }

    @Override
    @Nonnull
    public Long component1() {
        return getIdAccount();
    }

    @Override
    @Nonnull
    public String component2() {
        return getConsumerKey();
    }

    @Override
    @Nonnull
    public String component3() {
        return getConsumerSecret();
    }

    @Override
    @Nonnull
    public String component4() {
        return getTokenValue();
    }

    @Override
    @Nonnull
    public String component5() {
        return getTokenSecret();
    }

    @Override
    @Nonnull
    public LocalDate component6() {
        return getValidUntil();
    }

    @Override
    @Nonnull
    public Long value1() {
        return getIdAccount();
    }

    @Override
    @Nonnull
    public String value2() {
        return getConsumerKey();
    }

    @Override
    @Nonnull
    public String value3() {
        return getConsumerSecret();
    }

    @Override
    @Nonnull
    public String value4() {
        return getTokenValue();
    }

    @Override
    @Nonnull
    public String value5() {
        return getTokenSecret();
    }

    @Override
    @Nonnull
    public LocalDate value6() {
        return getValidUntil();
    }

    @Override
    @Nonnull
    public BricklinkTokensRecord value1(@Nonnull Long value) {
        setIdAccount(value);
        return this;
    }

    @Override
    @Nonnull
    public BricklinkTokensRecord value2(@Nonnull String value) {
        setConsumerKey(value);
        return this;
    }

    @Override
    @Nonnull
    public BricklinkTokensRecord value3(@Nonnull String value) {
        setConsumerSecret(value);
        return this;
    }

    @Override
    @Nonnull
    public BricklinkTokensRecord value4(@Nonnull String value) {
        setTokenValue(value);
        return this;
    }

    @Override
    @Nonnull
    public BricklinkTokensRecord value5(@Nonnull String value) {
        setTokenSecret(value);
        return this;
    }

    @Override
    @Nonnull
    public BricklinkTokensRecord value6(@Nonnull LocalDate value) {
        setValidUntil(value);
        return this;
    }

    @Override
    @Nonnull
    public BricklinkTokensRecord values(@Nonnull Long value1, @Nonnull String value2, @Nonnull String value3, @Nonnull String value4, @Nonnull String value5, @Nonnull LocalDate value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BricklinkTokensRecord
     */
    public BricklinkTokensRecord() {
        super(BricklinkTokens.BRICKLINK_TOKENS);
    }

    /**
     * Create a detached, initialised BricklinkTokensRecord
     */
    @ConstructorProperties({ "idAccount", "consumerKey", "consumerSecret", "tokenValue", "tokenSecret", "validUntil" })
    public BricklinkTokensRecord(@Nonnull Long idAccount, @Nonnull String consumerKey, @Nonnull String consumerSecret, @Nonnull String tokenValue, @Nonnull String tokenSecret, @Nonnull LocalDate validUntil) {
        super(BricklinkTokens.BRICKLINK_TOKENS);

        setIdAccount(idAccount);
        setConsumerKey(consumerKey);
        setConsumerSecret(consumerSecret);
        setTokenValue(tokenValue);
        setTokenSecret(tokenSecret);
        setValidUntil(validUntil);
    }
}
