/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.*;
import jooq.tables.Color;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "color",
    schema = "public"
)
public class ColorRecord extends UpdatableRecordImpl<ColorRecord> {

    private static final long serialVersionUID = 255626747;

    /**
     * Setter for <code>public.color.id</code>.
     */
    public ColorRecord setId(@Nullable Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.color.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ColorRecord
     */
    public ColorRecord() {
        super(Color.COLOR);
    }

    /**
     * Create a detached, initialised ColorRecord
     */
    @ConstructorProperties({ "id" })
    public ColorRecord(@Nullable Long id) {
        super(Color.COLOR);

        setId(id);
        resetChangedOnNotNull();
    }
}
