/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jooq.tables.Constants;
import org.jooq.impl.TableRecordImpl;

import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "constants",
    schema = "public"
)
public class ConstantsRecord extends TableRecordImpl<ConstantsRecord> {

    private static final long serialVersionUID = -953526586;

    /**
     * Setter for <code>public.constants.stud_to_mm_factor</code>. The factor to
     * convert a stud dimension to millimeter.
     */
    public ConstantsRecord setStudToMmFactor(@Nullable Short value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.constants.stud_to_mm_factor</code>. The factor to
     * convert a stud dimension to millimeter.
     */
    @Column(name = "stud_to_mm_factor")
    @Nullable
    public Short getStudToMmFactor() {
        return (Short) get(0);
    }

    /**
     * Setter for <code>public.constants.cm_to_mm_factor</code>. The factor to
     * convert a centimeter dimension to millimeter.
     */
    public ConstantsRecord setCmToMmFactor(@Nullable Short value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.constants.cm_to_mm_factor</code>. The factor to
     * convert a centimeter dimension to millimeter.
     */
    @Column(name = "cm_to_mm_factor")
    @Nullable
    public Short getCmToMmFactor() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.constants.stud_height_mm</code>. The height of a
     * stud in millimeter.
     */
    public ConstantsRecord setStudHeightMm(@Nullable Double value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.constants.stud_height_mm</code>. The height of a
     * stud in millimeter.
     */
    @Column(name = "stud_height_mm")
    @Nullable
    public Double getStudHeightMm() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConstantsRecord
     */
    public ConstantsRecord() {
        super(Constants.CONSTANTS);
    }

    /**
     * Create a detached, initialised ConstantsRecord
     */
    @ConstructorProperties({ "studToMmFactor", "cmToMmFactor", "studHeightMm" })
    public ConstantsRecord(@Nullable Short studToMmFactor, @Nullable Short cmToMmFactor, @Nullable Double studHeightMm) {
        super(Constants.CONSTANTS);

        setStudToMmFactor(studToMmFactor);
        setCmToMmFactor(cmToMmFactor);
        setStudHeightMm(studHeightMm);
        resetChangedOnNotNull();
    }
}
