/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import jooq.tables.ContainerType;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "container_type",
    schema = "public"
)
public class ContainerTypeRecord extends UpdatableRecordImpl<ContainerTypeRecord> {

    private static final long serialVersionUID = -180542311;

    /**
     * Setter for <code>public.container_type.id</code>.
     */
    public ContainerTypeRecord setId(@Nullable Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.container_type.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    @Nullable
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.container_type.name</code>.
     */
    public ContainerTypeRecord setName(@Nonnull String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.container_type.name</code>.
     */
    @Column(name = "name", nullable = false, length = 1024)
    @NotNull
    @Size(max = 1024)
    @Nonnull
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.container_type.min_lockers</code>.
     */
    public ContainerTypeRecord setMinLockers(@Nonnull Short value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.container_type.min_lockers</code>.
     */
    @Column(name = "min_lockers", nullable = false)
    @NotNull
    @Nonnull
    public Short getMinLockers() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.container_type.max_lockers</code>.
     */
    public ContainerTypeRecord setMaxLockers(@Nonnull Short value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.container_type.max_lockers</code>.
     */
    @Column(name = "max_lockers", nullable = false)
    @NotNull
    @Nonnull
    public Short getMaxLockers() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.container_type.number_formatting</code>.
     */
    public ContainerTypeRecord setNumberFormatting(@Nullable String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.container_type.number_formatting</code>.
     */
    @Column(name = "number_formatting", length = 256)
    @Size(max = 256)
    @Nullable
    public String getNumberFormatting() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ContainerTypeRecord
     */
    public ContainerTypeRecord() {
        super(ContainerType.CONTAINER_TYPE);
    }

    /**
     * Create a detached, initialised ContainerTypeRecord
     */
    @ConstructorProperties({ "id", "name", "minLockers", "maxLockers", "numberFormatting" })
    public ContainerTypeRecord(@Nullable Long id, @Nonnull String name, @Nonnull Short minLockers, @Nonnull Short maxLockers, @Nullable String numberFormatting) {
        super(ContainerType.CONTAINER_TYPE);

        setId(id);
        setName(name);
        setMinLockers(minLockers);
        setMaxLockers(maxLockers);
        setNumberFormatting(numberFormatting);
        resetChangedOnNotNull();
    }
}
