/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import jooq.tables.ItemType;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * item_type is considered as a table of constants, there is not sequence.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "item_type",
    schema = "public",
    uniqueConstraints = {
        @UniqueConstraint(name = "unique_item_type_on_code", columnNames = { "code" })
    }
)
public class ItemTypeRecord extends UpdatableRecordImpl<ItemTypeRecord> {

    private static final long serialVersionUID = 1592382087;

    /**
     * Setter for <code>public.item_type.id</code>.
     */
    public ItemTypeRecord setId(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.item_type.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    @NotNull
    @Nonnull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.item_type.name</code>.
     */
    public ItemTypeRecord setName(@Nonnull String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.item_type.name</code>.
     */
    @Column(name = "name", nullable = false, length = 1024)
    @NotNull
    @Size(max = 1024)
    @Nonnull
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.item_type.code</code>.
     */
    public ItemTypeRecord setCode(@Nonnull String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.item_type.code</code>.
     */
    @Column(name = "code", nullable = false, length = 1)
    @NotNull
    @Size(max = 1)
    @Nonnull
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item_type.dimension_in_stud</code>.
     */
    public ItemTypeRecord setDimensionInStud(@Nullable Boolean value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.item_type.dimension_in_stud</code>.
     */
    @Column(name = "dimension_in_stud")
    @Nullable
    public Boolean getDimensionInStud() {
        return (Boolean) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemTypeRecord
     */
    public ItemTypeRecord() {
        super(ItemType.ITEM_TYPE);
    }

    /**
     * Create a detached, initialised ItemTypeRecord
     */
    @ConstructorProperties({ "id", "name", "code", "dimensionInStud" })
    public ItemTypeRecord(@Nonnull Long id, @Nonnull String name, @Nonnull String code, @Nullable Boolean dimensionInStud) {
        super(ItemType.ITEM_TYPE);

        setId(id);
        setName(name);
        setCode(code);
        setDimensionInStud(dimensionInStud);
        resetChangedOnNotNull();
    }
}
