/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jooq.tables.ItemSubType;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "item_sub_type",
    schema = "public"
)
public class ItemSubTypeRecord extends UpdatableRecordImpl<ItemSubTypeRecord> {

    private static final long serialVersionUID = -1182442833;

    /**
     * Setter for <code>public.item_sub_type.id_base_item_type</code>.
     */
    public ItemSubTypeRecord setIdBaseItemType(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.item_sub_type.id_base_item_type</code>.
     */
    @Column(name = "id_base_item_type", nullable = false)
    @NotNull
    @Nonnull
    public Long getIdBaseItemType() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.item_sub_type.id_sub_item_type</code>.
     */
    public ItemSubTypeRecord setIdSubItemType(@Nonnull Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.item_sub_type.id_sub_item_type</code>.
     */
    @Column(name = "id_sub_item_type", nullable = false)
    @NotNull
    @Nonnull
    public Long getIdSubItemType() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemSubTypeRecord
     */
    public ItemSubTypeRecord() {
        super(ItemSubType.ITEM_SUB_TYPE);
    }

    /**
     * Create a detached, initialised ItemSubTypeRecord
     */
    @ConstructorProperties({ "idBaseItemType", "idSubItemType" })
    public ItemSubTypeRecord(@Nonnull Long idBaseItemType, @Nonnull Long idSubItemType) {
        super(ItemSubType.ITEM_SUB_TYPE);

        setIdBaseItemType(idBaseItemType);
        setIdSubItemType(idSubItemType);
        resetChangedOnNotNull();
    }
}
