/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jooq.tables.LockedAccount;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "locked_account",
    schema = "public"
)
public class LockedAccountRecord extends UpdatableRecordImpl<LockedAccountRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1664630238;

    /**
     * Setter for <code>public.locked_account.id_account</code>.
     */
    public LockedAccountRecord setIdAccount(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.locked_account.id_account</code>.
     */
    @Id
    @Column(name = "id_account", nullable = false, precision = 64)
    @NotNull
    @Nonnull
    public Long getIdAccount() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Long> field1() {
        return LockedAccount.LOCKED_ACCOUNT.ID_ACCOUNT;
    }

    @Override
    @Nonnull
    public Long component1() {
        return getIdAccount();
    }

    @Override
    @Nonnull
    public Long value1() {
        return getIdAccount();
    }

    @Override
    @Nonnull
    public LockedAccountRecord value1(@Nonnull Long value) {
        setIdAccount(value);
        return this;
    }

    @Override
    @Nonnull
    public LockedAccountRecord values(@Nonnull Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LockedAccountRecord
     */
    public LockedAccountRecord() {
        super(LockedAccount.LOCKED_ACCOUNT);
    }

    /**
     * Create a detached, initialised LockedAccountRecord
     */
    @ConstructorProperties({ "idAccount" })
    public LockedAccountRecord(@Nonnull Long idAccount) {
        super(LockedAccount.LOCKED_ACCOUNT);

        setIdAccount(idAccount);
    }
}
