/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jooq.tables.Locker;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "locker",
    schema = "public"
)
public class LockerRecord extends UpdatableRecordImpl<LockerRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = 1449868370;

    /**
     * Setter for <code>public.locker.id</code>.
     */
    public LockerRecord setId(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.locker.id</code>.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, precision = 64)
    @Nonnull
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.locker.id_locker_size</code>.
     */
    public LockerRecord setIdLockerSize(@Nullable Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.locker.id_locker_size</code>.
     */
    @Column(name = "id_locker_size", precision = 64)
    @Nullable
    public Long getIdLockerSize() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Long> field1() {
        return Locker.LOCKER.ID;
    }

    @Override
    @Nonnull
    public Field<Long> field2() {
        return Locker.LOCKER.ID_LOCKER_SIZE;
    }

    @Override
    @Nonnull
    public Long component1() {
        return getId();
    }

    @Override
    @Nullable
    public Long component2() {
        return getIdLockerSize();
    }

    @Override
    @Nonnull
    public Long value1() {
        return getId();
    }

    @Override
    @Nullable
    public Long value2() {
        return getIdLockerSize();
    }

    @Override
    @Nonnull
    public LockerRecord value1(@Nonnull Long value) {
        setId(value);
        return this;
    }

    @Override
    @Nonnull
    public LockerRecord value2(@Nullable Long value) {
        setIdLockerSize(value);
        return this;
    }

    @Override
    @Nonnull
    public LockerRecord values(@Nonnull Long value1, @Nullable Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LockerRecord
     */
    public LockerRecord() {
        super(Locker.LOCKER);
    }

    /**
     * Create a detached, initialised LockerRecord
     */
    @ConstructorProperties({ "id", "idLockerSize" })
    public LockerRecord(@Nonnull Long id, @Nullable Long idLockerSize) {
        super(Locker.LOCKER);

        setId(id);
        setIdLockerSize(idLockerSize);
    }
}
