/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import java.beans.ConstructorProperties;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;

import jooq.tables.PrivateContainer;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "private_container",
    schema = "public"
)
public class PrivateContainerRecord extends UpdatableRecordImpl<PrivateContainerRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1337645806;

    /**
     * Setter for <code>public.private_container.id_container</code>.
     */
    public PrivateContainerRecord setIdContainer(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.private_container.id_container</code>.
     */
    @Id
    @Column(name = "id_container", nullable = false, precision = 64)
    @NotNull
    @Nonnull
    public Long getIdContainer() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.private_container.id_account</code>.
     */
    public PrivateContainerRecord setIdAccount(@Nullable Long value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.private_container.id_account</code>.
     */
    @Column(name = "id_account", precision = 64)
    @Nullable
    public Long getIdAccount() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Long> field1() {
        return PrivateContainer.PRIVATE_CONTAINER.ID_CONTAINER;
    }

    @Override
    @Nonnull
    public Field<Long> field2() {
        return PrivateContainer.PRIVATE_CONTAINER.ID_ACCOUNT;
    }

    @Override
    @Nonnull
    public Long component1() {
        return getIdContainer();
    }

    @Override
    @Nullable
    public Long component2() {
        return getIdAccount();
    }

    @Override
    @Nonnull
    public Long value1() {
        return getIdContainer();
    }

    @Override
    @Nullable
    public Long value2() {
        return getIdAccount();
    }

    @Override
    @Nonnull
    public PrivateContainerRecord value1(@Nonnull Long value) {
        setIdContainer(value);
        return this;
    }

    @Override
    @Nonnull
    public PrivateContainerRecord value2(@Nullable Long value) {
        setIdAccount(value);
        return this;
    }

    @Override
    @Nonnull
    public PrivateContainerRecord values(@Nonnull Long value1, @Nullable Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrivateContainerRecord
     */
    public PrivateContainerRecord() {
        super(PrivateContainer.PRIVATE_CONTAINER);
    }

    /**
     * Create a detached, initialised PrivateContainerRecord
     */
    @ConstructorProperties({ "idContainer", "idAccount" })
    public PrivateContainerRecord(@Nonnull Long idContainer, @Nullable Long idAccount) {
        super(PrivateContainer.PRIVATE_CONTAINER);

        setIdContainer(idContainer);
        setIdAccount(idAccount);
    }
}
