/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jooq.tables.SharedContainer;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Entity
@Table(
    name = "shared_container",
    schema = "public"
)
public class SharedContainerRecord extends UpdatableRecordImpl<SharedContainerRecord> {

    private static final long serialVersionUID = -406277305;

    /**
     * Setter for <code>public.shared_container.id_container</code>.
     */
    public SharedContainerRecord setIdContainer(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_container.id_container</code>.
     */
    @Id
    @Column(name = "id_container", nullable = false)
    @NotNull
    @Nonnull
    public Long getIdContainer() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SharedContainerRecord
     */
    public SharedContainerRecord() {
        super(SharedContainer.SHARED_CONTAINER);
    }

    /**
     * Create a detached, initialised SharedContainerRecord
     */
    @ConstructorProperties({ "idContainer" })
    public SharedContainerRecord(@Nonnull Long idContainer) {
        super(SharedContainer.SHARED_CONTAINER);

        setIdContainer(idContainer);
        resetChangedOnNotNull();
    }
}
