/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;
import jooq.tables.SharedContainer;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;
import java.beans.ConstructorProperties;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(
    name = "shared_container",
    schema = "public"
)
public class SharedContainerRecord extends UpdatableRecordImpl<SharedContainerRecord> implements Record1<Long> {

    private static final long serialVersionUID = 1880586543;

    /**
     * Setter for <code>public.shared_container.id_container</code>.
     */
    public SharedContainerRecord setIdContainer(@Nonnull Long value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.shared_container.id_container</code>.
     */
    @Id
    @Column(name = "id_container", nullable = false, precision = 64)
    @NotNull
    @Nonnull
    public Long getIdContainer() {
        return (Long) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    @Nonnull
    public Row1<Long> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    @Nonnull
    public Field<Long> field1() {
        return SharedContainer.SHARED_CONTAINER.ID_CONTAINER;
    }

    @Override
    @Nonnull
    public Long component1() {
        return getIdContainer();
    }

    @Override
    @Nonnull
    public Long value1() {
        return getIdContainer();
    }

    @Override
    @Nonnull
    public SharedContainerRecord value1(@Nonnull Long value) {
        setIdContainer(value);
        return this;
    }

    @Override
    @Nonnull
    public SharedContainerRecord values(@Nonnull Long value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SharedContainerRecord
     */
    public SharedContainerRecord() {
        super(SharedContainer.SHARED_CONTAINER);
    }

    /**
     * Create a detached, initialised SharedContainerRecord
     */
    @ConstructorProperties({ "idContainer" })
    public SharedContainerRecord(@Nonnull Long idContainer) {
        super(SharedContainer.SHARED_CONTAINER);

        setIdContainer(idContainer);
    }
}
