/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Domains;
import jooq.Keys;
import jooq.Public;
import jooq.tables.Account.AccountPath;
import jooq.tables.records.BricksetTokensRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BricksetTokens extends TableImpl<BricksetTokensRecord> {

    private static final long serialVersionUID = -736393808;

    /**
     * The reference instance of <code>public.brickset_tokens</code>
     */
    public static final BricksetTokens BRICKSET_TOKENS = new BricksetTokens();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<BricksetTokensRecord> getRecordType() {
        return BricksetTokensRecord.class;
    }

    /**
     * The column <code>public.brickset_tokens.id_account</code>.
     */
    public final TableField<BricksetTokensRecord, Long> ID_ACCOUNT = createField(DSL.name("id_account"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.brickset_tokens.api_key</code>.
     */
    public final TableField<BricksetTokensRecord, String> API_KEY = createField(DSL.name("api_key"), Domains.DOMAIN_TOKEN.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.brickset_tokens.username</code>.
     */
    public final TableField<BricksetTokensRecord, String> USERNAME = createField(DSL.name("username"), Domains.DOMAIN_USERNAME.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.brickset_tokens.password</code>.
     */
    public final TableField<BricksetTokensRecord, String> PASSWORD = createField(DSL.name("password"), Domains.DOMAIN_PASSWORD.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.brickset_tokens.valid_until</code>.
     */
    public final TableField<BricksetTokensRecord, LocalDate> VALID_UNTIL = createField(DSL.name("valid_until"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("(now() + '1 year'::interval)"), SQLDataType.LOCALDATE)), this, "");

    private BricksetTokens(Name alias, Table<BricksetTokensRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BricksetTokens(Name alias, Table<BricksetTokensRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.brickset_tokens</code> table reference
     */
    public BricksetTokens(String alias) {
        this(DSL.name(alias), BRICKSET_TOKENS);
    }

    /**
     * Create an aliased <code>public.brickset_tokens</code> table reference
     */
    public BricksetTokens(Name alias) {
        this(alias, BRICKSET_TOKENS);
    }

    /**
     * Create a <code>public.brickset_tokens</code> table reference
     */
    public BricksetTokens() {
        this(DSL.name("brickset_tokens"), null);
    }

    public <O extends Record> BricksetTokens(Table<O> path, ForeignKey<O, BricksetTokensRecord> childPath, InverseForeignKey<O, BricksetTokensRecord> parentPath) {
        super(path, childPath, parentPath, BRICKSET_TOKENS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BricksetTokensPath extends BricksetTokens implements Path<BricksetTokensRecord> {

        private static final long serialVersionUID = -736393808;
        public <O extends Record> BricksetTokensPath(Table<O> path, ForeignKey<O, BricksetTokensRecord> childPath, InverseForeignKey<O, BricksetTokensRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BricksetTokensPath(Name alias, Table<BricksetTokensRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BricksetTokensPath as(String alias) {
            return new BricksetTokensPath(DSL.name(alias), this);
        }

        @Override
        public BricksetTokensPath as(Name alias) {
            return new BricksetTokensPath(alias, this);
        }

        @Override
        public BricksetTokensPath as(Table<?> alias) {
            return new BricksetTokensPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public UniqueKey<BricksetTokensRecord> getPrimaryKey() {
        return Keys.PK_BRICKSET_TOKENS;
    }

    @Override
    @Nonnull
    public List<ForeignKey<BricksetTokensRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BRICKSET_TOKENS__FK_BRICKSET_TOKENS_TO_ACCOUNT);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.BRICKSET_TOKENS__FK_BRICKSET_TOKENS_TO_ACCOUNT, null);

        return _account;
    }

    @Override
    @Nonnull
    public BricksetTokens as(String alias) {
        return new BricksetTokens(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public BricksetTokens as(Name alias) {
        return new BricksetTokens(alias, this);
    }

    @Override
    @Nonnull
    public BricksetTokens as(Table<?> alias) {
        return new BricksetTokens(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public BricksetTokens rename(String name) {
        return new BricksetTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public BricksetTokens rename(Name name) {
        return new BricksetTokens(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public BricksetTokens rename(Table<?> name) {
        return new BricksetTokens(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricksetTokens where(Condition condition) {
        return new BricksetTokens(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricksetTokens where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricksetTokens where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricksetTokens where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public BricksetTokens where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public BricksetTokens where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public BricksetTokens where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public BricksetTokens where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricksetTokens whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricksetTokens whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
