/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Domains;
import jooq.Keys;
import jooq.Public;
import jooq.tables.Account.AccountPath;
import jooq.tables.records.BricklinkTokensRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class BricklinkTokens extends TableImpl<BricklinkTokensRecord> {

    private static final long serialVersionUID = 1811026894;

    /**
     * The reference instance of <code>public.bricklink_tokens</code>
     */
    public static final BricklinkTokens BRICKLINK_TOKENS = new BricklinkTokens();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<BricklinkTokensRecord> getRecordType() {
        return BricklinkTokensRecord.class;
    }

    /**
     * The column <code>public.bricklink_tokens.id_account</code>.
     */
    public final TableField<BricklinkTokensRecord, Long> ID_ACCOUNT = createField(DSL.name("id_account"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.bricklink_tokens.consumer_key</code>.
     */
    public final TableField<BricklinkTokensRecord, String> CONSUMER_KEY = createField(DSL.name("consumer_key"), Domains.DOMAIN_TOKEN.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.bricklink_tokens.consumer_secret</code>.
     */
    public final TableField<BricklinkTokensRecord, String> CONSUMER_SECRET = createField(DSL.name("consumer_secret"), Domains.DOMAIN_TOKEN.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.bricklink_tokens.token_value</code>.
     */
    public final TableField<BricklinkTokensRecord, String> TOKEN_VALUE = createField(DSL.name("token_value"), Domains.DOMAIN_TOKEN.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.bricklink_tokens.token_secret</code>.
     */
    public final TableField<BricklinkTokensRecord, String> TOKEN_SECRET = createField(DSL.name("token_secret"), Domains.DOMAIN_TOKEN.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.bricklink_tokens.valid_until</code>.
     */
    public final TableField<BricklinkTokensRecord, LocalDate> VALID_UNTIL = createField(DSL.name("valid_until"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("(now() + '1 year'::interval)"), SQLDataType.LOCALDATE)), this, "");

    private BricklinkTokens(Name alias, Table<BricklinkTokensRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BricklinkTokens(Name alias, Table<BricklinkTokensRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.bricklink_tokens</code> table reference
     */
    public BricklinkTokens(String alias) {
        this(DSL.name(alias), BRICKLINK_TOKENS);
    }

    /**
     * Create an aliased <code>public.bricklink_tokens</code> table reference
     */
    public BricklinkTokens(Name alias) {
        this(alias, BRICKLINK_TOKENS);
    }

    /**
     * Create a <code>public.bricklink_tokens</code> table reference
     */
    public BricklinkTokens() {
        this(DSL.name("bricklink_tokens"), null);
    }

    public <O extends Record> BricklinkTokens(Table<O> path, ForeignKey<O, BricklinkTokensRecord> childPath, InverseForeignKey<O, BricklinkTokensRecord> parentPath) {
        super(path, childPath, parentPath, BRICKLINK_TOKENS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BricklinkTokensPath extends BricklinkTokens implements Path<BricklinkTokensRecord> {

        private static final long serialVersionUID = 1811026894;
        public <O extends Record> BricklinkTokensPath(Table<O> path, ForeignKey<O, BricklinkTokensRecord> childPath, InverseForeignKey<O, BricklinkTokensRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BricklinkTokensPath(Name alias, Table<BricklinkTokensRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BricklinkTokensPath as(String alias) {
            return new BricklinkTokensPath(DSL.name(alias), this);
        }

        @Override
        public BricklinkTokensPath as(Name alias) {
            return new BricklinkTokensPath(alias, this);
        }

        @Override
        public BricklinkTokensPath as(Table<?> alias) {
            return new BricklinkTokensPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public UniqueKey<BricklinkTokensRecord> getPrimaryKey() {
        return Keys.PK_BRICKLINK_TOKENS;
    }

    @Override
    @Nonnull
    public List<ForeignKey<BricklinkTokensRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BRICKLINK_TOKENS__FK_BRICKLINK_TOKENS_TO_ACCOUNT);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.BRICKLINK_TOKENS__FK_BRICKLINK_TOKENS_TO_ACCOUNT, null);

        return _account;
    }

    @Override
    @Nonnull
    public BricklinkTokens as(String alias) {
        return new BricklinkTokens(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public BricklinkTokens as(Name alias) {
        return new BricklinkTokens(alias, this);
    }

    @Override
    @Nonnull
    public BricklinkTokens as(Table<?> alias) {
        return new BricklinkTokens(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public BricklinkTokens rename(String name) {
        return new BricklinkTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public BricklinkTokens rename(Name name) {
        return new BricklinkTokens(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public BricklinkTokens rename(Table<?> name) {
        return new BricklinkTokens(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricklinkTokens where(Condition condition) {
        return new BricklinkTokens(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricklinkTokens where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricklinkTokens where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricklinkTokens where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public BricklinkTokens where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public BricklinkTokens where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public BricklinkTokens where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public BricklinkTokens where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricklinkTokens whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public BricklinkTokens whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
