/*
 * This file is generated by jOOQ.
 */
package jooq.tables;

import jooq.Keys;
import jooq.Public;
import jooq.tables.records.BricksetTokensRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BricksetTokens extends TableImpl<BricksetTokensRecord> {

    private static final long serialVersionUID = 1924075168;

    /**
     * The reference instance of <code>public.brickset_tokens</code>
     */
    public static final BricksetTokens BRICKSET_TOKENS = new BricksetTokens();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<BricksetTokensRecord> getRecordType() {
        return BricksetTokensRecord.class;
    }

    /**
     * The column <code>public.brickset_tokens.id_account</code>.
     */
    public final TableField<BricksetTokensRecord, Long> ID_ACCOUNT = createField(DSL.name("id_account"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.brickset_tokens.api_key</code>.
     */
    public final TableField<BricksetTokensRecord, String> API_KEY = createField(DSL.name("api_key"), jooq.Domains.DOMAIN_TOKEN.getDataType(), this, "");

    /**
     * The column <code>public.brickset_tokens.username</code>.
     */
    public final TableField<BricksetTokensRecord, String> USERNAME = createField(DSL.name("username"), jooq.Domains.DOMAIN_USERNAME.getDataType(), this, "");

    /**
     * The column <code>public.brickset_tokens.password</code>.
     */
    public final TableField<BricksetTokensRecord, String> PASSWORD = createField(DSL.name("password"), jooq.Domains.DOMAIN_PASSWORD.getDataType(), this, "");

    /**
     * The column <code>public.brickset_tokens.valid_until</code>.
     */
    public final TableField<BricksetTokensRecord, LocalDate> VALID_UNTIL = createField(DSL.name("valid_until"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field("(now() + '1 year'::interval)", SQLDataType.LOCALDATE)), this, "");

    private BricksetTokens(Name alias, Table<BricksetTokensRecord> aliased) {
        this(alias, aliased, null);
    }

    private BricksetTokens(Name alias, Table<BricksetTokensRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.brickset_tokens</code> table reference
     */
    public BricksetTokens(String alias) {
        this(DSL.name(alias), BRICKSET_TOKENS);
    }

    /**
     * Create an aliased <code>public.brickset_tokens</code> table reference
     */
    public BricksetTokens(Name alias) {
        this(alias, BRICKSET_TOKENS);
    }

    /**
     * Create a <code>public.brickset_tokens</code> table reference
     */
    public BricksetTokens() {
        this(DSL.name("brickset_tokens"), null);
    }

    public <O extends Record> BricksetTokens(Table<O> child, ForeignKey<O, BricksetTokensRecord> key) {
        super(child, key, BRICKSET_TOKENS);
    }

    @Override
    @Nonnull
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public UniqueKey<BricksetTokensRecord> getPrimaryKey() {
        return Keys.PK_BRICKSET_TOKENS;
    }

    @Override
    @Nonnull
    public List<ForeignKey<BricksetTokensRecord, ?>> getReferences() {
        return Arrays.asList(Keys.BRICKSET_TOKENS__FK_BRICKSET_TOKENS_TO_ACCOUNT);
    }

    private transient Account _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.BRICKSET_TOKENS__FK_BRICKSET_TOKENS_TO_ACCOUNT);

        return _account;
    }

    @Override
    @Nonnull
    public BricksetTokens as(String alias) {
        return new BricksetTokens(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public BricksetTokens as(Name alias) {
        return new BricksetTokens(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public BricksetTokens rename(String name) {
        return new BricksetTokens(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public BricksetTokens rename(Name name) {
        return new BricksetTokens(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row5<Long, String, String, String, LocalDate> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
