/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;

import jooq.Keys;
import jooq.Public;
import jooq.tables.records.ColorRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row1;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Color extends TableImpl<ColorRecord> {

    private static final long serialVersionUID = 66002448;

    /**
     * The reference instance of <code>public.color</code>
     */
    public static final Color COLOR = new Color();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<ColorRecord> getRecordType() {
        return ColorRecord.class;
    }

    /**
     * The column <code>public.color.id</code>.
     */
    public final TableField<ColorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    private Color(Name alias, Table<ColorRecord> aliased) {
        this(alias, aliased, null);
    }

    private Color(Name alias, Table<ColorRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.color</code> table reference
     */
    public Color(String alias) {
        this(DSL.name(alias), COLOR);
    }

    /**
     * Create an aliased <code>public.color</code> table reference
     */
    public Color(Name alias) {
        this(alias, COLOR);
    }

    /**
     * Create a <code>public.color</code> table reference
     */
    public Color() {
        this(DSL.name("color"), null);
    }

    public <O extends Record> Color(Table<O> child, ForeignKey<O, ColorRecord> key) {
        super(child, key, COLOR);
    }

    @Override
    @Nonnull
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public Identity<ColorRecord, Long> getIdentity() {
        return (Identity<ColorRecord, Long>) super.getIdentity();
    }

    @Override
    @Nonnull
    public UniqueKey<ColorRecord> getPrimaryKey() {
        return Keys.PK_COLOR;
    }

    @Override
    @Nonnull
    public Color as(String alias) {
        return new Color(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public Color as(Name alias) {
        return new Color(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public Color rename(String name) {
        return new Color(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public Color rename(Name name) {
        return new Color(name, null);
    }

    // -------------------------------------------------------------------------
    // Row1 type methods
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row1<Long> fieldsRow() {
        return (Row1) super.fieldsRow();
    }
}
