/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Public;
import jooq.tables.records.ConstantsRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Constants extends TableImpl<ConstantsRecord> {

    private static final long serialVersionUID = -809457980;

    /**
     * The reference instance of <code>public.constants</code>
     */
    public static final Constants CONSTANTS = new Constants();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<ConstantsRecord> getRecordType() {
        return ConstantsRecord.class;
    }

    /**
     * The column <code>public.constants.stud_to_mm_factor</code>. The factor to
     * convert a stud dimension to millimeter.
     */
    public final TableField<ConstantsRecord, Short> STUD_TO_MM_FACTOR = createField(DSL.name("stud_to_mm_factor"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("8"), SQLDataType.SMALLINT)), this, "The factor to convert a stud dimension to millimeter.");

    /**
     * The column <code>public.constants.cm_to_mm_factor</code>. The factor to
     * convert a centimeter dimension to millimeter.
     */
    public final TableField<ConstantsRecord, Short> CM_TO_MM_FACTOR = createField(DSL.name("cm_to_mm_factor"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("10"), SQLDataType.SMALLINT)), this, "The factor to convert a centimeter dimension to millimeter.");

    /**
     * The column <code>public.constants.stud_height_mm</code>. The height of a
     * stud in millimeter.
     */
    public final TableField<ConstantsRecord, Double> STUD_HEIGHT_MM = createField(DSL.name("stud_height_mm"), SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("1.7"), SQLDataType.DOUBLE)), this, "The height of a stud in millimeter.");

    private Constants(Name alias, Table<ConstantsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Constants(Name alias, Table<ConstantsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.constants</code> table reference
     */
    public Constants(String alias) {
        this(DSL.name(alias), CONSTANTS);
    }

    /**
     * Create an aliased <code>public.constants</code> table reference
     */
    public Constants(Name alias) {
        this(alias, CONSTANTS);
    }

    /**
     * Create a <code>public.constants</code> table reference
     */
    public Constants() {
        this(DSL.name("constants"), null);
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public Constants as(String alias) {
        return new Constants(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public Constants as(Name alias) {
        return new Constants(alias, this);
    }

    @Override
    @Nonnull
    public Constants as(Table<?> alias) {
        return new Constants(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public Constants rename(String name) {
        return new Constants(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public Constants rename(Name name) {
        return new Constants(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public Constants rename(Table<?> name) {
        return new Constants(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Constants where(Condition condition) {
        return new Constants(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Constants where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Constants where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Constants where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public Constants where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public Constants where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public Constants where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public Constants where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Constants whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Constants whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
