/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Public;
import jooq.tables.Account.AccountPath;
import jooq.tables.records.LockedAccountRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LockedAccount extends TableImpl<LockedAccountRecord> {

    private static final long serialVersionUID = -1148440166;

    /**
     * The reference instance of <code>public.locked_account</code>
     */
    public static final LockedAccount LOCKED_ACCOUNT = new LockedAccount();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<LockedAccountRecord> getRecordType() {
        return LockedAccountRecord.class;
    }

    /**
     * The column <code>public.locked_account.id_account</code>.
     */
    public final TableField<LockedAccountRecord, Long> ID_ACCOUNT = createField(DSL.name("id_account"), SQLDataType.BIGINT.nullable(false), this, "");

    private LockedAccount(Name alias, Table<LockedAccountRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LockedAccount(Name alias, Table<LockedAccountRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.locked_account</code> table reference
     */
    public LockedAccount(String alias) {
        this(DSL.name(alias), LOCKED_ACCOUNT);
    }

    /**
     * Create an aliased <code>public.locked_account</code> table reference
     */
    public LockedAccount(Name alias) {
        this(alias, LOCKED_ACCOUNT);
    }

    /**
     * Create a <code>public.locked_account</code> table reference
     */
    public LockedAccount() {
        this(DSL.name("locked_account"), null);
    }

    public <O extends Record> LockedAccount(Table<O> path, ForeignKey<O, LockedAccountRecord> childPath, InverseForeignKey<O, LockedAccountRecord> parentPath) {
        super(path, childPath, parentPath, LOCKED_ACCOUNT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LockedAccountPath extends LockedAccount implements Path<LockedAccountRecord> {

        private static final long serialVersionUID = -1148440166;
        public <O extends Record> LockedAccountPath(Table<O> path, ForeignKey<O, LockedAccountRecord> childPath, InverseForeignKey<O, LockedAccountRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LockedAccountPath(Name alias, Table<LockedAccountRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LockedAccountPath as(String alias) {
            return new LockedAccountPath(DSL.name(alias), this);
        }

        @Override
        public LockedAccountPath as(Name alias) {
            return new LockedAccountPath(alias, this);
        }

        @Override
        public LockedAccountPath as(Table<?> alias) {
            return new LockedAccountPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public UniqueKey<LockedAccountRecord> getPrimaryKey() {
        return Keys.PK_LOCKED_ACCOUNT;
    }

    @Override
    @Nonnull
    public List<ForeignKey<LockedAccountRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LOCKED_ACCOUNT__FK_LOCKED_ACCOUNT_TO_ACCOUNT);
    }

    private transient AccountPath _account;

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public AccountPath account() {
        if (_account == null)
            _account = new AccountPath(this, Keys.LOCKED_ACCOUNT__FK_LOCKED_ACCOUNT_TO_ACCOUNT, null);

        return _account;
    }

    @Override
    @Nonnull
    public LockedAccount as(String alias) {
        return new LockedAccount(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public LockedAccount as(Name alias) {
        return new LockedAccount(alias, this);
    }

    @Override
    @Nonnull
    public LockedAccount as(Table<?> alias) {
        return new LockedAccount(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public LockedAccount rename(String name) {
        return new LockedAccount(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public LockedAccount rename(Name name) {
        return new LockedAccount(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public LockedAccount rename(Table<?> name) {
        return new LockedAccount(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public LockedAccount where(Condition condition) {
        return new LockedAccount(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public LockedAccount where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public LockedAccount where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public LockedAccount where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public LockedAccount where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public LockedAccount where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public LockedAccount where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public LockedAccount where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public LockedAccount whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public LockedAccount whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
