/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Nonnull;
import javax.annotation.processing.Generated;

import jooq.Keys;
import jooq.Public;
import jooq.tables.records.PrivateContainerRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrivateContainer extends TableImpl<PrivateContainerRecord> {

    private static final long serialVersionUID = 951550089;

    /**
     * The reference instance of <code>public.private_container</code>
     */
    public static final PrivateContainer PRIVATE_CONTAINER = new PrivateContainer();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<PrivateContainerRecord> getRecordType() {
        return PrivateContainerRecord.class;
    }

    /**
     * The column <code>public.private_container.id_container</code>.
     */
    public final TableField<PrivateContainerRecord, Long> ID_CONTAINER = createField(DSL.name("id_container"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.private_container.id_account</code>.
     */
    public final TableField<PrivateContainerRecord, Long> ID_ACCOUNT = createField(DSL.name("id_account"), SQLDataType.BIGINT, this, "");

    private PrivateContainer(Name alias, Table<PrivateContainerRecord> aliased) {
        this(alias, aliased, null);
    }

    private PrivateContainer(Name alias, Table<PrivateContainerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.private_container</code> table reference
     */
    public PrivateContainer(String alias) {
        this(DSL.name(alias), PRIVATE_CONTAINER);
    }

    /**
     * Create an aliased <code>public.private_container</code> table reference
     */
    public PrivateContainer(Name alias) {
        this(alias, PRIVATE_CONTAINER);
    }

    /**
     * Create a <code>public.private_container</code> table reference
     */
    public PrivateContainer() {
        this(DSL.name("private_container"), null);
    }

    public <O extends Record> PrivateContainer(Table<O> child, ForeignKey<O, PrivateContainerRecord> key) {
        super(child, key, PRIVATE_CONTAINER);
    }

    @Override
    @Nonnull
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public UniqueKey<PrivateContainerRecord> getPrimaryKey() {
        return Keys.PK_PRIVATE_CONTAINER;
    }

    @Override
    @Nonnull
    public List<ForeignKey<PrivateContainerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PRIVATE_CONTAINER__FK_PRIVATE_CONTAINER_TO_CONTAINER, Keys.PRIVATE_CONTAINER__FK_PRIVATE_CONTAINER_TO_ACCOUNT);
    }

    private transient Container _container;
    private transient Account _account;

    /**
     * Get the implicit join path to the <code>public.container</code> table.
     */
    public Container container() {
        if (_container == null)
            _container = new Container(this, Keys.PRIVATE_CONTAINER__FK_PRIVATE_CONTAINER_TO_CONTAINER);

        return _container;
    }

    /**
     * Get the implicit join path to the <code>public.account</code> table.
     */
    public Account account() {
        if (_account == null)
            _account = new Account(this, Keys.PRIVATE_CONTAINER__FK_PRIVATE_CONTAINER_TO_ACCOUNT);

        return _account;
    }

    @Override
    @Nonnull
    public PrivateContainer as(String alias) {
        return new PrivateContainer(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public PrivateContainer as(Name alias) {
        return new PrivateContainer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public PrivateContainer rename(String name) {
        return new PrivateContainer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public PrivateContainer rename(Name name) {
        return new PrivateContainer(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    @Nonnull
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
