/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Domains;
import jooq.Keys;
import jooq.Public;
import jooq.tables.ColorInfo.ColorInfoPath;
import jooq.tables.ColorSource.ColorSourcePath;
import jooq.tables.records.RgbaRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Rgba extends TableImpl<RgbaRecord> {

    private static final long serialVersionUID = -1402343708;

    /**
     * The reference instance of <code>public.rgba</code>
     */
    public static final Rgba RGBA = new Rgba();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<RgbaRecord> getRecordType() {
        return RgbaRecord.class;
    }

    /**
     * The column <code>public.rgba.id</code>.
     */
    public final TableField<RgbaRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.rgba.red</code>.
     */
    public final TableField<RgbaRecord, Short> RED = createField(DSL.name("red"), Domains.DOMAIN_COLOR_COMPONENT.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.rgba.green</code>.
     */
    public final TableField<RgbaRecord, Short> GREEN = createField(DSL.name("green"), Domains.DOMAIN_COLOR_COMPONENT.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.rgba.blue</code>.
     */
    public final TableField<RgbaRecord, Short> BLUE = createField(DSL.name("blue"), Domains.DOMAIN_COLOR_COMPONENT.getDataType().nullable(false), this, "");

    /**
     * The column <code>public.rgba.alpha</code>.
     */
    public final TableField<RgbaRecord, Float> ALPHA = createField(DSL.name("alpha"), Domains.DOMAIN_ALPHA_COMPONENT.getDataType().nullable(false), this, "");

    private Rgba(Name alias, Table<RgbaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Rgba(Name alias, Table<RgbaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.rgba</code> table reference
     */
    public Rgba(String alias) {
        this(DSL.name(alias), RGBA);
    }

    /**
     * Create an aliased <code>public.rgba</code> table reference
     */
    public Rgba(Name alias) {
        this(alias, RGBA);
    }

    /**
     * Create a <code>public.rgba</code> table reference
     */
    public Rgba() {
        this(DSL.name("rgba"), null);
    }

    public <O extends Record> Rgba(Table<O> path, ForeignKey<O, RgbaRecord> childPath, InverseForeignKey<O, RgbaRecord> parentPath) {
        super(path, childPath, parentPath, RGBA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RgbaPath extends Rgba implements Path<RgbaRecord> {

        private static final long serialVersionUID = -1402343708;
        public <O extends Record> RgbaPath(Table<O> path, ForeignKey<O, RgbaRecord> childPath, InverseForeignKey<O, RgbaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RgbaPath(Name alias, Table<RgbaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RgbaPath as(String alias) {
            return new RgbaPath(DSL.name(alias), this);
        }

        @Override
        public RgbaPath as(Name alias) {
            return new RgbaPath(alias, this);
        }

        @Override
        public RgbaPath as(Table<?> alias) {
            return new RgbaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public Identity<RgbaRecord, Long> getIdentity() {
        return (Identity<RgbaRecord, Long>) super.getIdentity();
    }

    @Override
    @Nonnull
    public UniqueKey<RgbaRecord> getPrimaryKey() {
        return Keys.PK_RGPA;
    }

    @Override
    @Nonnull
    public List<UniqueKey<RgbaRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_RGBA_ON_COMPONENTS);
    }

    private transient ColorInfoPath _colorInfo;

    /**
     * Get the implicit to-many join path to the <code>public.color_info</code>
     * table
     */
    public ColorInfoPath colorInfo() {
        if (_colorInfo == null)
            _colorInfo = new ColorInfoPath(this, null, Keys.COLOR_INFO__FK_COLOR_INFO_TO_RGBA.getInverseKey());

        return _colorInfo;
    }

    /**
     * Get the implicit many-to-many join path to the
     * <code>public.color_source</code> table
     */
    public ColorSourcePath colorSource() {
        return colorInfo().colorSource();
    }

    @Override
    @Nonnull
    public Rgba as(String alias) {
        return new Rgba(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public Rgba as(Name alias) {
        return new Rgba(alias, this);
    }

    @Override
    @Nonnull
    public Rgba as(Table<?> alias) {
        return new Rgba(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public Rgba rename(String name) {
        return new Rgba(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public Rgba rename(Name name) {
        return new Rgba(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public Rgba rename(Table<?> name) {
        return new Rgba(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Rgba where(Condition condition) {
        return new Rgba(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Rgba where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Rgba where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Rgba where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public Rgba where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public Rgba where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public Rgba where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public Rgba where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Rgba whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public Rgba whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
