/*
 * This file is generated by jOOQ.
 */
package jooq.tables;


import jooq.Keys;
import jooq.Public;
import jooq.tables.Container.ContainerPath;
import jooq.tables.records.SharedContainerRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SharedContainer extends TableImpl<SharedContainerRecord> {

    private static final long serialVersionUID = 1306171542;

    /**
     * The reference instance of <code>public.shared_container</code>
     */
    public static final SharedContainer SHARED_CONTAINER = new SharedContainer();

    /**
     * The class holding records for this type
     */
    @Override
    @Nonnull
    public Class<SharedContainerRecord> getRecordType() {
        return SharedContainerRecord.class;
    }

    /**
     * The column <code>public.shared_container.id_container</code>.
     */
    public final TableField<SharedContainerRecord, Long> ID_CONTAINER = createField(DSL.name("id_container"), SQLDataType.BIGINT.nullable(false), this, "");

    private SharedContainer(Name alias, Table<SharedContainerRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SharedContainer(Name alias, Table<SharedContainerRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.shared_container</code> table reference
     */
    public SharedContainer(String alias) {
        this(DSL.name(alias), SHARED_CONTAINER);
    }

    /**
     * Create an aliased <code>public.shared_container</code> table reference
     */
    public SharedContainer(Name alias) {
        this(alias, SHARED_CONTAINER);
    }

    /**
     * Create a <code>public.shared_container</code> table reference
     */
    public SharedContainer() {
        this(DSL.name("shared_container"), null);
    }

    public <O extends Record> SharedContainer(Table<O> path, ForeignKey<O, SharedContainerRecord> childPath, InverseForeignKey<O, SharedContainerRecord> parentPath) {
        super(path, childPath, parentPath, SHARED_CONTAINER);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SharedContainerPath extends SharedContainer implements Path<SharedContainerRecord> {

        private static final long serialVersionUID = 1306171542;
        public <O extends Record> SharedContainerPath(Table<O> path, ForeignKey<O, SharedContainerRecord> childPath, InverseForeignKey<O, SharedContainerRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SharedContainerPath(Name alias, Table<SharedContainerRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SharedContainerPath as(String alias) {
            return new SharedContainerPath(DSL.name(alias), this);
        }

        @Override
        public SharedContainerPath as(Name alias) {
            return new SharedContainerPath(alias, this);
        }

        @Override
        public SharedContainerPath as(Table<?> alias) {
            return new SharedContainerPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    @Nonnull
    public UniqueKey<SharedContainerRecord> getPrimaryKey() {
        return Keys.PK_SHARED_CONTAINER;
    }

    @Override
    @Nonnull
    public List<ForeignKey<SharedContainerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SHARED_CONTAINER__FK_SHARED_CONTAINER_TO_CONTAINER);
    }

    private transient ContainerPath _container;

    /**
     * Get the implicit join path to the <code>public.container</code> table.
     */
    public ContainerPath container() {
        if (_container == null)
            _container = new ContainerPath(this, Keys.SHARED_CONTAINER__FK_SHARED_CONTAINER_TO_CONTAINER, null);

        return _container;
    }

    @Override
    @Nonnull
    public SharedContainer as(String alias) {
        return new SharedContainer(DSL.name(alias), this);
    }

    @Override
    @Nonnull
    public SharedContainer as(Name alias) {
        return new SharedContainer(alias, this);
    }

    @Override
    @Nonnull
    public SharedContainer as(Table<?> alias) {
        return new SharedContainer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public SharedContainer rename(String name) {
        return new SharedContainer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public SharedContainer rename(Name name) {
        return new SharedContainer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @Nonnull
    public SharedContainer rename(Table<?> name) {
        return new SharedContainer(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public SharedContainer where(Condition condition) {
        return new SharedContainer(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public SharedContainer where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public SharedContainer where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public SharedContainer where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public SharedContainer where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public SharedContainer where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public SharedContainer where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    @PlainSQL
    public SharedContainer where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public SharedContainer whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @Nonnull
    public SharedContainer whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
